### ISSUE TITLE
Updated favorites counter only displaying on pets show page.

### ISSUE THREAD

**Issue by moosehandlr** [moosehandlr/Adopt_Dont_Shop_Paired#13]
Favorites counter only displays updated count when visiting pets show page.
Every other page displays "0" count.

**Comment by ajtran303** [comment]
https://github.com/moosehandlr/Adopt_Dont_Shop_Paired/blob/a433e849cf0449686983f4829cbba3ade3cdc006/app/views/layouts/application.html.erb#L20

The reason it says there's 0 favorites on every other page is because `@favorites` is nil on those pages.
So I think one strategy would be to make sure that `@favorites` is never nil.

Since that instance variable `favorites` needs to be passed around to ALL pages, maybe the logic would have to go into the ApplicationController super class? Just a shot in the dark.

**Comment by ajtran303** [comment]
Definitely the right strategy. [Controller Cleanup:](https://backend.turing.io/module2/lessons/cart_implementation)

> It’s from the line in our application.html.erb where we call @cart.total_count. @cart is nil because, although we set it in our SongsController#index and CartController#update, we didn’t set it in every action. 

```ruby
# application_controller.rb

  helper_method :cart   # We make this new method a helper_method so that we can access it in the views.

  def cart
    @cart ||= Cart.new(session[:cart])
  end
```

So it's a three step process.
Compose a `favorites` helper method in the super class.
Then remove all invocations of `Favorites.new` from the child classes.
Finally, wherever the views call the `@favorites` instance variable, make them call the `favorites` helper method instead.

**Comment by moosehandlr** [comment]
Favorites counter 

>Displays updated favorites count on every page.
